# Generated by Django 5.2.4 on 2025-07-11 23:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KayakUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('display_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(default='', max_length=128)),
                ('last_name', models.CharField(default='', max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('city', models.CharField(default='', max_length=128)),
                ('county', models.CharField(default='', max_length=128)),
                ('state', models.CharField(default='', max_length=50)),
                ('signup_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('birthday', models.DateField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
