# Generated by Django 5.2.4 on 2025-07-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kayakuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
