# Generated by Django 5.2.4 on 2025-07-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_kayakuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayakuser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
