# Generated by Django 5.2.4 on 2025-07-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_kayakuser_groups_kayakuser_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='kayakuser',
            name='picture',
            field=models.ImageField(default='nopicture.jpg', upload_to='images/'),
        ),
    ]
