# Generated by Django 5.2.4 on 2025-07-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_kayakuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayakuser',
            name='city',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='kayakuser',
            name='county',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='kayakuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='kayakuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='kayakuser',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
