# Generated by Django 5.2.4 on 2025-07-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_kayakuser_city_alter_kayakuser_county_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kayakuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='kayakuser',
            name='county',
        ),
        migrations.RemoveField(
            model_name='kayakuser',
            name='state',
        ),
    ]
