# Generated by Django 5.2.4 on 2025-07-12 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchinfo', '0010_country_abbr'),
        ('users', '0007_remove_kayakuser_city_remove_kayakuser_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kayakuser',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='launchinfo.city'),
        ),
        migrations.AddField(
            model_name='kayakuser',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='launchinfo.country'),
        ),
        migrations.AddField(
            model_name='kayakuser',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='launchinfo.county'),
        ),
        migrations.AddField(
            model_name='kayakuser',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='launchinfo.state'),
        ),
    ]
