# Generated by Django 5.2.4 on 2025-07-12 13:55

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_kayakuser_city_kayakuser_country_kayakuser_county_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kayakuser',
            name='picture',
        ),
        migrations.AddField(
            model_name='kayakuser',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='noone.jpg', upload_to='avatars'),
        ),
    ]
