# Generated by Django 5.2.4 on 2025-07-12 14:29

import imagekit.models.fields
import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_thumbnail_kayakuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayakuser',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='noone.jpg', upload_to=users.models.generate_unique_avatar_name),
        ),
    ]
