# Generated by Django 5.2.4 on 2025-07-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_kayakuser_city_alter_kayakuser_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayakuser',
            name='signup_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
