# Generated by Django 5.2.4 on 2025-07-18 00:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_kayakuser_signup_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kayakuser',
            options={'ordering': ['display_name'], 'verbose_name': 'Kayak User', 'verbose_name_plural': 'Kayak Users'},
        ),
        migrations.AlterField(
            model_name='kayakuser',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
