/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    CreateCity: typeof import('./src/components/CreateCity.vue')['default']
    CreateCounty: typeof import('./src/components/CreateCounty.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LaunchDetail: typeof import('./src/components/LaunchDetail.vue')['default']
    LaunchList: typeof import('./src/components/LaunchList.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TripDetail: typeof import('./src/components/TripDetail.vue')['default']
    TripList: typeof import('./src/components/TripList.vue')['default']
    WaterDetail: typeof import('./src/components/WaterDetail.vue')['default']
    WaterList: typeof import('./src/components/WaterList.vue')['default']
  }
}
