# Generated by Django 5.2.4 on 2025-07-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathroom_type', models.SmallIntegerField(choices=[(0, 'None'), (1, 'Outhouse'), (2, 'Plumbed'), (3, 'Nearby')])),
                ('ramp_type', models.SmallIntegerField(choices=[(0, 'None'), (1, 'Hard Surfaced'), (2, 'Carry Down'), (3, 'Gravel')])),
                ('parking_type', models.SmallIntegerField(choices=[(0, 'None'), (1, 'Gravel'), (2, 'Paved')])),
                ('pay_parking', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=128)),
            ],
        ),
    ]
