# Generated by Django 5.2.4 on 2025-07-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchinfo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facilities',
        ),
        migrations.AddField(
            model_name='launch',
            name='bathroom_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='bathroom_type',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'Outhouse'), (2, 'Plumbed'), (3, 'Nearby')], default=0),
        ),
        migrations.AddField(
            model_name='launch',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='launch',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='launch',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='launch',
            name='parking_type',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'Gravel'), (2, 'Paved')], default=1),
        ),
        migrations.AddField(
            model_name='launch',
            name='pay_info',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='pay_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='launch',
            name='ramp_type',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'Hard Surfaced'), (2, 'Carry Down'), (3, 'Gravel')], default=1),
        ),
        migrations.AlterField(
            model_name='launch',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
