# Generated by Django 5.2.4 on 2025-07-11 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchinfo', '0002_delete_facilities_launch_bathroom_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
