# Generated by Django 5.2.4 on 2025-07-11 19:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchinfo', '0003_launch_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
