# Generated by Django 5.2.4 on 2025-07-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchinfo', '0004_launch_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='city',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='launch',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
    ]
