# Generated by Django 5.2.4 on 2025-07-11 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchinfo', '0005_launch_city_launch_state'),
        ('waterinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='body_of_water',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='waterinfo.water'),
        ),
        migrations.AddField(
            model_name='launch',
            name='county',
            field=models.CharField(default='', max_length=128),
        ),
    ]
