# Generated by Django 5.2.4 on 2025-07-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchinfo', '0006_launch_body_of_water_launch_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='pay_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
