# Generated by Django 5.2.4 on 2025-07-12 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchinfo', '0007_launch_comment_alter_launch_pay_info'),
        ('waterinfo', '0002_water_hectares_water_latitude_water_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbr', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='launch',
            name='city',
        ),
        migrations.RemoveField(
            model_name='launch',
            name='county',
        ),
        migrations.RemoveField(
            model_name='launch',
            name='state',
        ),
        migrations.AlterField(
            model_name='launch',
            name='body_of_water',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waterinfo.water'),
        ),
    ]
