# Generated by Django 5.2.4 on 2025-07-12 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchinfo', '0008_city_country_county_state_remove_launch_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='launchinfo.city'),
        ),
        migrations.AddField(
            model_name='launch',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='launchinfo.country'),
        ),
        migrations.AddField(
            model_name='launch',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='launchinfo.county'),
        ),
        migrations.AddField(
            model_name='launch',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='launchinfo.state'),
        ),
    ]
