# Generated by Django 5.2.4 on 2025-07-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchinfo', '0009_launch_city_launch_country_launch_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='abbr',
            field=models.CharField(default='', max_length=5),
        ),
    ]
