# Generated by Django 5.2.4 on 2025-07-12 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchinfo', '0010_country_abbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='launchinfo.county'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='launchinfo.state'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='county',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='launchinfo.state'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='launchinfo.country'),
            preserve_default=False,
        ),
    ]
