# Generated by Django 5.2.4 on 2025-07-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launchinfo', '0012_remove_city_county_remove_city_state_and_more'),
        ('users', '0012_alter_kayakuser_city_alter_kayakuser_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='County',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
