# Generated by Django 5.2.4 on 2025-07-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchinfo', '0014_alter_launch_city_alter_launch_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
