# Generated by Django 5.2.4 on 2025-07-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchinfo', '0015_alter_launch_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='bathrooms',
            field=models.SmallIntegerField(default=0),
        ),
    ]
