# Generated by Django 5.2.4 on 2025-07-13 22:03

import django.db.models.deletion
import launchinfo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchinfo', '0016_alter_launch_bathrooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(upload_to=launchinfo.models.generate_unique_launch_name)),
                ('launch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='launchinfo.launch')),
            ],
        ),
    ]
