# Generated by Django 5.2.4 on 2025-07-14 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchinfo', '0017_launchimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='main_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launch_main_image', to='launchinfo.launchimage'),
        ),
    ]
