# Generated by Django 5.2.4 on 2025-07-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchinfo', '0018_launch_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='bathroom_type',
            field=models.CharField(choices=[(0, 'None'), (1, 'Outhouse'), (2, 'Plumbed'), (3, 'Nearby')], default=0),
        ),
    ]
