# Generated by Django 5.2.4 on 2025-07-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchinfo', '0020_alter_launch_bathroom_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='launchimage',
            name='caption',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
