# Generated by Django 5.2.4 on 2025-07-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayakutils', '0002_alter_city_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
