# Generated by Django 5.2.4 on 2025-07-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('city', models.CharField(default='', max_length=128)),
                ('county', models.CharField(default='', max_length=128)),
                ('state', models.CharField(default='', max_length=50)),
                ('water_type', models.SmallIntegerField(choices=[(0, 'River'), (1, 'Lake'), (2, 'Other')], default=1)),
                ('acres', models.FloatField(default=0)),
            ],
        ),
    ]
