# Generated by Django 5.2.4 on 2025-07-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='water',
            name='hectares',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='water',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='water',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='water',
            name='max_depth_feet',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='water',
            name='max_depth_meters',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='water',
            name='water_type',
            field=models.SmallIntegerField(choices=[(0, 'River'), (1, 'Lake'), (2, 'Resivoir'), (3, 'Other')], default=1),
        ),
    ]
