# Generated by Django 5.2.4 on 2025-07-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterinfo', '0002_water_hectares_water_latitude_water_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='water',
            name='city',
        ),
        migrations.RemoveField(
            model_name='water',
            name='county',
        ),
        migrations.RemoveField(
            model_name='water',
            name='state',
        ),
    ]
