# Generated by Django 5.2.4 on 2025-07-12 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayakutils', '0001_initial'),
        ('waterinfo', '0003_remove_water_city_remove_water_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='water',
            name='city',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kayakutils.city'),
        ),
        migrations.AddField(
            model_name='water',
            name='country',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kayakutils.country'),
        ),
        migrations.AddField(
            model_name='water',
            name='county',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kayakutils.county'),
        ),
        migrations.AddField(
            model_name='water',
            name='state',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kayakutils.state'),
        ),
    ]
