# Generated by Django 5.2.4 on 2025-07-12 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayakutils', '0001_initial'),
        ('waterinfo', '0004_water_city_water_country_water_county_water_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kayakutils.city'),
        ),
        migrations.AlterField(
            model_name='water',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kayakutils.country'),
        ),
        migrations.AlterField(
            model_name='water',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kayakutils.county'),
        ),
        migrations.AlterField(
            model_name='water',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kayakutils.state'),
        ),
    ]
