# Generated by Django 5.2.4 on 2025-07-12 18:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterinfo', '0005_alter_water_city_alter_water_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='water',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='water',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
