# Generated by Django 5.2.4 on 2025-07-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterinfo', '0006_water_date_created_water_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
