# Generated by Django 5.2.4 on 2025-07-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterinfo', '0007_alter_water_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='max_depth_meters',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
