# Generated by Django 5.2.4 on 2025-07-13 22:03

import django.db.models.deletion
import waterinfo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterinfo', '0008_alter_water_max_depth_meters'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(upload_to=waterinfo.models.generate_unique_water_name)),
                ('water', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterinfo.water')),
            ],
        ),
    ]
