# Generated by Django 5.2.4 on 2025-07-14 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterinfo', '0009_waterimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='water',
            name='main_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_main_image', to='waterinfo.waterimage'),
        ),
    ]
