# Generated by Django 5.2.4 on 2025-07-25 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayakutils', '0003_alter_country_name_alter_state_name'),
        ('waterinfo', '0010_water_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kayakutils.city'),
        ),
        migrations.AlterField(
            model_name='water',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_main_image', to='waterinfo.waterimage'),
        ),
    ]
