# Generated by Django 5.2.4 on 2025-07-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterinfo', '0011_alter_water_city_alter_water_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='water',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
