# Generated by Django 5.2.4 on 2025-07-11 22:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('launchinfo', '0007_launch_comment_alter_launch_pay_info'),
        ('waterinfo', '0002_water_hectares_water_latitude_water_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('body_of_water', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='waterinfo.water')),
                ('end_launch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trip_end_launch', to='launchinfo.launch')),
                ('start_launch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trip_start_launch', to='launchinfo.launch')),
            ],
        ),
    ]
