# Generated by Django 5.2.4 on 2025-07-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripinfo', '0002_trip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
