# Generated by Django 5.2.4 on 2025-07-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripinfo', '0003_trip_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
