# Generated by Django 5.2.4 on 2025-07-13 22:03

import django.db.models.deletion
import tripinfo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripinfo', '0005_alter_trip_end_time_alter_trip_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(upload_to=tripinfo.models.generate_unique_trip_name)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripinfo.trip')),
            ],
        ),
    ]
